// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    app_settings: {
        name: "app_settings";
        parameters: Record<string, never>;
        result: Array<{
          /** Key from settings.SPECS */
          setting_key: string;
          /** JSON-encoded so the type survives the round trip */
          setting_value: string;
          /** When this value was written */
          updated_at: string;
          /** Who changed it, for the panel history line */
          updated_by: string;
        }>;
      };
    fulfilling_lines: {
        name: "fulfilling_lines";
        parameters: Record<string, never>;
        result: Array<{
          /** Surrogate key */
          RESTOCK_REQUEST_KEY: number;
          /** Degenerate dimension — quote business key */
          QUOTE_ID: string;
          /** Business key */
          PART_ID: string;
          /** SKU / component name. Display this, not PART_KEY. */
          PART_NAME: string;
          /** Business key */
          WAREHOUSE_ID: string;
          /** CRITICAL / HIGH / MEDIUM / LOW */
          URGENCY_LEVEL: string;
          /** Quantity requested */
          REQUESTED_QTY: number;
          /** Quantity confirmed after real-time check */
          CONFIRMED_QTY: number;
          /** Confirmed minus requested */
          VARIANCE_QTY: number;
          /** PM free-text reasoning for the approve/reject decision on this line */
          NOTE: string;
          /** Date the PM decided */
          DECISION_DATE_KEY: number;
        }>;
      };
    pending_quotes: {
        name: "pending_quotes";
        parameters: Record<string, never>;
        result: Array<{
          /** Business key matching gold_dev.supply_chain_analytics.fact_restock_request.QUOTE_ID */
          quote_id: string;
          /** Row creation timestamp */
          created_at: string;
          /** When the Teams notification was dispatched */
          teams_sent_at: string;
          /** @sqlType BIGINT */
          total_lines: number;
          /** @sqlType BIGINT */
          pending_lines: number;
          /** @sqlType BIGINT */
          needs_review_lines: number;
          /** @sqlType BIGINT */
          approved_lines: number;
          /** @sqlType BIGINT */
          rejected_lines: number;
          /** @sqlType INT */
          top_urgency_rank: number;
          /** @sqlType DECIMAL(28,2) */
          total_exposure: number;
          /** @sqlType STRING */
          finding_types: string;
        }>;
      };
    quote_header: {
        name: "quote_header";
        parameters: {
          /** STRING - use sql.string() */
          quoteId: SQLStringMarker;
        };
        result: Array<{
          /** Business key matching gold_dev.supply_chain_analytics.fact_restock_request.QUOTE_ID */
          quote_id: string;
          /** Genie Agent natural-language assumption/reasoning report for this quote */
          summary_report: string;
          /** Reference ID of the Adaptive Card sent to Teams */
          teams_message_id: string;
          /** When the Teams notification was dispatched */
          teams_sent_at: string;
          /** Deep link to the Databricks Review App for this quote */
          databricks_preview_url: string;
          /** Optional approver comments explaining the decision */
          decision_comments: string;
          /** Agent that created this quote record (default: supervisor_agent) */
          created_by: string;
          /** Row creation timestamp */
          created_at: string;
          /** Last modification timestamp */
          updated_at: string;
        }>;
      };
    quote_lines: {
        name: "quote_lines";
        parameters: {
          /** STRING - use sql.string() */
          quoteId: SQLStringMarker;
        };
        result: Array<{
          /** Surrogate key */
          RESTOCK_REQUEST_KEY: number;
          /** Degenerate dimension — quote business key */
          QUOTE_ID: string;
          /** Degenerate dimension — fulfilled line business key */
          RESTOCK_REQUEST_ID: string;
          /** Business key */
          PART_ID: string;
          /** SKU / component name. Display this, not PART_KEY. */
          PART_NAME: string;
          /** Business key */
          WAREHOUSE_ID: string;
          /** Which action this row asks for: PURCHASE, TRANSFER, RENEGOTIATE, RESOURCE, RECALIBRATE, REVIEW_STOCK. REQUIRED to read this table correctly -- the row grain is no longer purchases only, so summing REQUESTED_QTY across action types mixes units bought with units moved. Added 2026-09-05; see docs/schema_changes_gold_dev_analytics.md */
          ACTION_TYPE: string;
          /** Which detector raised it: STOCKOUT_RISK, CASCADE_BLOCK, REDEPLOYMENT, DEAD_CAPITAL, LEADTIME_SIGNAL, DEMAND_SHIFT, SUPPLIER_ECONOMICS, MOQ_UNECONOMIC */
          FINDING_TYPE: string;
          /** The finding subject at its own grain (part@warehouse, parent@warehouse, supplier:ID, part/supplier). Lets suppression match a decision to a finding for non-part-grain actions, which PART_KEY alone cannot */
          SUBJECT_KEY: string;
          /** Business key */
          SOURCE_WAREHOUSE_ID: string;
          /** Business key */
          RECOMMENDED_SUPPLIER_ID: string;
          /** Exposure when the recommendation was raised. Enables re-surfacing on exposure growth rather than time alone, and is what the decision ledger needs to prove realised ROI */
          EXPOSURE_AT_DECISION: number;
          /** PENDING_APPROVAL / APPROVED / REJECTED / FULFILLING / NEEDS_REVIEW / COMPLETED */
          REQUEST_STATUS: string;
          /** CRITICAL / HIGH / MEDIUM / LOW */
          URGENCY_LEVEL: string;
          /** APPROVED / REJECTED / null if undecided */
          DECISION: string;
          /** Stock on hand at quote time */
          CURRENT_STOCK_QTY: number;
          /** Reorder point at quote time */
          REORDER_POINT_QTY: number;
          /** Quantity requested */
          REQUESTED_QTY: number;
          /** Quantity confirmed after real-time check */
          CONFIRMED_QTY: number;
          /** Confirmed minus requested */
          VARIANCE_QTY: number;
          /** Date the quote line was requested */
          REQUESTED_DATE_KEY: number;
          /** Date the PM decided */
          DECISION_DATE_KEY: number;
          /** Date the Restock Agent fulfilled the line */
          FULFILLED_DATE_KEY: number;
          /** PM free-text reasoning for the approve/reject decision on this line */
          NOTE: string;
          /** Structured reason the PM chose alongside NOTE: NOT_A_PROBLEM | ALREADY_HANDLED | CANNOT_ACT_NOW | NUMBERS_WRONG | OTHER */
          DECISION_REASON: string;
        }>;
      };
  }
}
