// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    pending_quotes: {
        name: "pending_quotes";
        parameters: Record<string, never>;
        result: Array<{
          /** Business key matching gold_dev.supply_chain_analytics.fact_restock_request.QUOTE_ID */
          quote_id: string;
          /** Row creation timestamp */
          created_at: string;
          /** When the Teams notification was dispatched */
          teams_sent_at: string;
          /** @sqlType BIGINT */
          total_lines: number;
          /** @sqlType BIGINT */
          pending_lines: number;
          /** @sqlType BIGINT */
          approved_lines: number;
          /** @sqlType BIGINT */
          rejected_lines: number;
          /** @sqlType INT */
          top_urgency_rank: number;
        }>;
      };
    quote_header: {
        name: "quote_header";
        parameters: {
          /** STRING - use sql.string() */
          quoteId: SQLStringMarker;
        };
        result: Array<{
          /** Business key matching gold_dev.supply_chain_analytics.fact_restock_request.QUOTE_ID */
          quote_id: string;
          /** Genie Agent natural-language assumption/reasoning report for this quote */
          summary_report: string;
          /** Reference ID of the Adaptive Card sent to Teams */
          teams_message_id: string;
          /** When the Teams notification was dispatched */
          teams_sent_at: string;
          /** Deep link to the Databricks Review App for this quote */
          databricks_preview_url: string;
          /** Optional approver comments explaining the decision */
          decision_comments: string;
          /** Agent that created this quote record (default: supervisor_agent) */
          created_by: string;
          /** Row creation timestamp */
          created_at: string;
          /** Last modification timestamp */
          updated_at: string;
        }>;
      };
    quote_lines: {
        name: "quote_lines";
        parameters: {
          /** STRING - use sql.string() */
          quoteId: SQLStringMarker;
        };
        result: Array<{
          /** Surrogate key */
          RESTOCK_REQUEST_KEY: number;
          /** Degenerate dimension — quote business key */
          QUOTE_ID: string;
          /** Degenerate dimension — fulfilled line business key */
          RESTOCK_REQUEST_ID: string;
          /** Business key */
          PART_ID: string;
          /** Part name */
          PART_NAME: string;
          /** Business key */
          WAREHOUSE_ID: string;
          /** PENDING_APPROVAL / APPROVED / REJECTED / FULFILLING / NEEDS_REVIEW / COMPLETED */
          REQUEST_STATUS: string;
          /** CRITICAL / HIGH / MEDIUM / LOW */
          URGENCY_LEVEL: string;
          /** APPROVED / REJECTED / null if undecided */
          DECISION: string;
          /** Stock on hand at quote time */
          CURRENT_STOCK_QTY: number;
          /** Reorder point at quote time */
          REORDER_POINT_QTY: number;
          /** Quantity requested */
          REQUESTED_QTY: number;
          /** Quantity confirmed after real-time check */
          CONFIRMED_QTY: number;
          /** Confirmed minus requested */
          VARIANCE_QTY: number;
          /** Date the quote line was requested */
          REQUESTED_DATE_KEY: number;
          /** Date the PM decided */
          DECISION_DATE_KEY: number;
          /** Date the Restock Agent fulfilled the line */
          FULFILLED_DATE_KEY: number;
          /** PM free-text reasoning for the approve/reject decision on this line */
          NOTE: string;
        }>;
      };
  }
}
