"""The admin panel's copy of the settings registry must match the pipeline's.

`src/agentic_restock/settings.py` is authoritative, but the browser and the Node server
cannot import it, so `restock-review/shared/settingsSpec.ts` mirrors it. Nothing enforces
that at runtime: a client could set a value the panel accepts and the pipeline then
silently falls back on, which presents as "your system ignored me" weeks later and is
close to undiagnosable from the outside.

So the parity check lives here, in the suite that already runs on every change. It reads
the TypeScript as text rather than executing it -- there is no Node in this test
environment, and the failure mode it guards (someone edits one file and not the other) is
visible in the source either way.

Deliberately NOT checked: labels, help text and `affects`. Those are the client-facing
half and have no equivalent in Python; requiring them to match something would mean
inventing a Python home for prose that belongs in the UI.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from agentic_restock import settings as S

SPEC_TS = Path(__file__).resolve().parents[1] / "restock-review" / "shared" / "settingsSpec.ts"


def _ts_specs() -> dict[str, dict]:
    """Pull key/kind/default/min/max/choices out of the TypeScript registry.

    A small regex reader rather than a parser: the file is generated by hand from a fixed
    template, and a parser would be more machinery than the thing it checks.
    """
    if not SPEC_TS.exists():  # pragma: no cover - guarded by the test below
        return {}

    text = SPEC_TS.read_text()
    body = text.split("export const SETTINGS: SettingSpec[] = [", 1)[1]
    body = body.split("\n];", 1)[0]

    specs: dict[str, dict] = {}
    # Each entry starts at `key: '...'` and runs to the next one.
    chunks = re.split(r"\n  \{\n", body)
    for chunk in chunks:
        key_match = re.search(r"key:\s*'([^']+)'", chunk)
        if not key_match:
            continue
        key = key_match.group(1)

        kind = re.search(r"kind:\s*'([^']+)'", chunk)
        default = re.search(r"default:\s*([^,\n]+)", chunk)
        minimum = re.search(r"\n    min:\s*([-\d.]+)", chunk)
        maximum = re.search(r"\n    max:\s*([-\d.]+)", chunk)
        choices = re.findall(r"value:\s*'([^']+)'", chunk)

        raw_default = default.group(1).strip() if default else None
        if raw_default and raw_default.startswith("'"):
            parsed_default = raw_default.strip("'")
        elif raw_default is not None:
            parsed_default = float(raw_default)
        else:
            parsed_default = None

        specs[key] = {
            "kind": kind.group(1) if kind else None,
            "default": parsed_default,
            "min": float(minimum.group(1)) if minimum else None,
            "max": float(maximum.group(1)) if maximum else None,
            "choices": tuple(choices),
        }
    return specs


def test_the_typescript_registry_exists():
    assert SPEC_TS.exists(), f"{SPEC_TS} is missing -- the admin panel cannot validate anything"


def test_both_registries_define_the_same_keys():
    ts = _ts_specs()
    assert set(ts) == {spec.key for spec in S.SPECS}


@pytest.mark.parametrize("spec", S.SPECS, ids=lambda s: s.key)
def test_each_setting_agrees_on_kind_default_and_bounds(spec: S.Spec):
    ts = _ts_specs()[spec.key]

    assert ts["kind"] == spec.kind, f"{spec.key}: kind differs"

    if spec.kind == "choice":
        assert ts["default"] == spec.default, f"{spec.key}: default differs"
        assert ts["choices"] == spec.choices, f"{spec.key}: choices differ"
    else:
        assert float(ts["default"]) == float(spec.default), f"{spec.key}: default differs"
        assert ts["min"] == spec.minimum, f"{spec.key}: minimum differs"
        assert ts["max"] == spec.maximum, f"{spec.key}: maximum differs"


def test_a_drifted_default_would_actually_fail():
    """The parity test is only worth having if it can fail -- this proves the reader works
    rather than silently matching nothing."""
    ts = _ts_specs()
    assert ts, "the TypeScript reader returned nothing; the parity tests above are vacuous"
    assert ts["holding_rate"]["default"] == pytest.approx(S.DEFAULTS.holding_rate)
    assert json.dumps(sorted(ts)) == json.dumps(sorted(spec.key for spec in S.SPECS))
