"""End-to-end test script for the Teams Adaptive Card integration.

Usage:
    export TEAMS_WEBHOOK_URL="https://your-org.webhook.office.com/webhookb2/..."
    PYTHONPATH=src python3 scripts/test_teams_card.py

If TEAMS_WEBHOOK_URL is not set, it runs in dry-run mode (logs card JSON,
no HTTP call). Set the env var to send a real card to your Teams channel.
"""

import os
import sys

sys.path.insert(0, "src")

from agentic_restock.integrations.teams_webhook import (
    build_review_app_url,
    send_quote_card,
)

# --- Sample test quote ---
QUOTE_ID = "QT-TEST-DEMO01"

CANDIDATES = [
    {
        "item_id": "P1003",
        "item_name": "Front Ventilated Disc Brake Pad",
        "warehouse_id": "WH003",
        "current_stock_qty": 110,
        "reorder_point_qty": 200,
        "suggested_reorder_qty": 1690,
        "stockout_risk": "HIGH",
        "signal_type": "STOCK_THRESHOLD",
        "initial_urgency": "CRITICAL",
        "days_to_stockout": None,
        "threatened_assembly": None,
    },
    {
        "item_id": "P1006",
        "item_name": "6-Speed Automatic Transmission Assembly",
        "warehouse_id": "WH009",
        "current_stock_qty": 150,
        "reorder_point_qty": 150,
        "suggested_reorder_qty": 1050,
        "stockout_risk": "HIGH",
        "signal_type": "STOCK_THRESHOLD",
        "initial_urgency": "CRITICAL",
        "days_to_stockout": None,
        "threatened_assembly": None,
    },
    {
        "item_id": "BEARING-B220",
        "item_name": "Angular Contact Bearing B-220",
        "warehouse_id": "WH003",
        "current_stock_qty": 850,
        "reorder_point_qty": 500,
        "suggested_reorder_qty": 1150,
        "stockout_risk": "HIGH",
        "signal_type": "BOM_CASCADE_RISK",
        "initial_urgency": "HIGH",
        "days_to_stockout": None,
        "threatened_assembly": "ENGINE-A (1.5L K15C DualJet)",
    },
]

SUPERVISOR_SUMMARY = """### Restock Quote Summary — QT-TEST-DEMO01
**Generated by**: Manufacturing Inventory Intelligence Engine
**Run date**: 2026-08-28

---

#### 1. Signal Validation (Layer 1)
- **P1003 @ WH003**: CRITICAL — 110 units on hand vs 200 safety stock. Burn rate normal (anomaly z-score: 0.0). Signal is genuine.
- **P1006 @ WH009**: CRITICAL — exactly at safety stock (150/150). Consumption velocity stable.
- **BEARING-B220 @ WH003**: HIGH — BOM cascade: shortfall of 1,150 units threatens ENGINE-A assembly (P1001). Component stock above its own safety stock, but insufficient for production run.

#### 2. Procurement Intelligence (Layer 2)
- **P1003**: No open POs covering shortfall. **Option A**: Transfer 100 units from WH001 (0 days, ₹0 procurement cost). **Option B**: PO 1,590 units from SUPP-001 at ₹450/unit, 7-day lead.
- **P1006**: No network surplus. **Option B only**: PO 1,050 units from SUPP-002, 12-day lead, ₹9,800/unit.
- **BEARING-B220**: No open POs. **Option B**: PO 1,150 units from SUPP-003, 5-day lead, ₹85/unit.

#### 3. Manufacturing Constraints (Layer 3)
- **P1003** is a bottleneck component in the 1.5L K15C DualJet Engine (P1001). 420 engines at WH001 are threatened.
- **BEARING-B220** shortage constrains 4 brakes per engine assembly. Production value at risk: ₹18,50,000.

#### 4. Financial Decision Framing (Layer 4)
- **P1003 inaction cost**: ₹2,40,000/day halted production. Overstock holding cost at max MOQ: ₹28,500.
- **P1006 inaction cost**: ₹6,10,000/day. Overstock at MOQ: ₹40,000.
- **Recommendation**: Execute Option A (transfer) for P1003 immediately. Place POs for P1006 and BEARING-B220 today given 12-day and 5-day lead times respectively."""


def main() -> None:
    webhook_url = os.environ.get("TEAMS_WEBHOOK_URL")
    dry_run = not webhook_url

    if dry_run:
        print("=" * 60)
        print("ℹ️  TEAMS_WEBHOOK_URL not set — running in dry-run mode.")
        print("   Set the env var to send a real card to Teams.")
        print("   Example: export TEAMS_WEBHOOK_URL='https://...'")
        print("=" * 60)
    else:
        print(f"✅ TEAMS_WEBHOOK_URL is set. Sending real card to Teams...")

    # Build review deep link
    review_url = build_review_app_url(
        quote_id=QUOTE_ID,
        workspace_url=os.environ.get("DATABRICKS_HOST", "https://your-workspace.azuredatabricks.net"),
    )
    print(f"\nReview App URL: {review_url}")

    # Send the card
    result = send_quote_card(
        quote_id=QUOTE_ID,
        candidates=CANDIDATES,
        supervisor_summary=SUPERVISOR_SUMMARY,
        review_app_url=review_url,
        webhook_url=webhook_url,
        dry_run=dry_run,
    )

    print("\n--- Result ---")
    print(f"  teams_message_id : {result['teams_message_id']}")
    print(f"  sent_at          : {result['sent_at']}")
    print(f"  dry_run          : {result['dry_run']}")

    if not dry_run:
        print("\n✅ Check your Teams channel — the card should appear within a few seconds.")
    else:
        print("\n[Dry-run] No card was sent. Set TEAMS_WEBHOOK_URL to send for real.")


if __name__ == "__main__":
    main()
